### ISSUE TITLE
Anchor points and study truncation

### ISSUE THREAD

**Issue by alecloudenback** [JuliaActuary/ExperienceAnalysis.jl#2]
Currently, `exposures(basis,from,to,continued_exposure=false)` uses the `from` argument as the anchor point for anniversaries. Refactor to allow the study start to be incorporated? Currently process is a [little clunky](https://github.com/JuliaActuary/ExperienceAnalysis.jl#study-endstart-dates).

Alternative API could be: `exposure(basis,anniv_date,termination_date,study_start,study_end,continued_exposure=false)`

This is also not ideal because `termination_date` could be a date, or `nothing`, or `missing` or however user has data stored. Perhaps enforce that it must be a date or `nothing`?

**Comment by MatthewCaseres** [comment]
Some initial thoughts - https://gist.github.com/MatthewCaseres/d338f85d768025623dcded0dd92e33ec.

**Comment by alecloudenback** [comment]
First thinking about the exposed API and how it would look for users.

Currently, the method looks like:

```julia
exposures(basis,from,to,continued_exposure=false)
```

But if instead it was:

```julia
exposures(
	basis,
	issue,
	termination_date, # can be a concrete Date or missing if `study_end` is given
	continued_exposure=false;
 
	# kwargs
	study_start = nothing, # if nothing then start at `from`
	study_end = nothing,   # if nothing, continue through end of last exposure 

	)
```

Does this allow for the control/convenience you think we should have?

**Comment by MatthewCaseres** [comment]
I'm working on a PR which should come in the next couple of days, I think some of this will get worked out there.

I have another issue which is saying that we should remove continued exposure though - https://github.com/JuliaActuary/ExperienceAnalysis.jl/issues/8

**Comment by MatthewCaseres** [comment]
I believe this can be closed
