### ISSUE TITLE
remove continued_exposure

### ISSUE THREAD

**Issue by MatthewCaseres** [JuliaActuary/ExperienceAnalysis.jl#8]
Seems like just indicating that the interval is the final interval and contains the decrement we are analyzing will work. I am not sure how `continued_exposure` will work for `AnniversaryCalendar`. The equation is probably like $\frac{events}{exposures}$?

**Comment by alecloudenback** [comment]
I'm not sure I understand the alternative here. Don't we need that when the termination is different than the decrement of interest?

**Comment by MatthewCaseres** [comment]
I should spend time reviewing my old docs and the experience studies report, maybe this issue need not be raised.

I think continuing exposure is for questions like "what is the percentage of policies that lapse in duration 10?"

But the exposure will not be fully continued in AnniversaryCalendar using the current code, does this change the calculation in a meaningful way?

**Comment by MatthewCaseres** [comment]
This issue may be closed because it seems aligned with standard practices. Leaving open until verification of this.

**Comment by MatthewCaseres** [comment]
https://github.com/JuliaActuary/ExperienceAnalysis.jl/pull/21
