### ISSUE TITLE
Change representation of date intervals

### ISSUE THREAD

**Issue by MatthewCaseres** [JuliaActuary/ExperienceAnalysis.jl#9]
## How to interpret dates in this package?
suppose we get this result from `exposure` function

```
[(from = Date("2016-07-04"), to = Date("2017-07-04")), (from = Date("2017-07-04"), to = Date("2017-07-05"))]
```
because `res[1].to == res[2].from`, I assume that they both refer to the same time on the clock (midnight?) so that there is no overlap. But if we get this result 
```
[(from = Date("2016-07-04"), to = Date("2016-07-04"))]
```
then the interval of time represented by it contains only a single instant and has exposure of 0?

I propose an alternative - 

## How I would like to do it
first result
```
[(from = Date("2016-07-04"), to = Date("2017-07-03")), (from = Date("2017-07-04"), to = Date("2017-07-05"))]
```
second result
```
[(from = Date("2016-07-04"), to = Date("2016-07-04"))]
```

### interpretation

supposing we have implemented `study_start` and `study_end`

How I interpret inputs - 
* `issue` is the `Dates.Date` containing the `Dates.Instant` where the policy was issued
* `termination` is the `Dates.Date` containing the `Dates.Instant` where the policy was terminated
* `study_start` includes the entire day, starts at midnight
* `study_end` includes the entire day, ends at `23:59.9999...` military time

How I interpret the outputs - 
* `tuple.from` is the beginning of the date interval. How does this relate to the `Date.Instant` where policy is issued?
    * If `issue < study_start` then the first interval's `tuple.from` refers to midnight/beginning of day, so that the entire day is included.
    * If `issue >= study_start` then the first interval's `tuple.from` might most accurately be a `Dates.Instant`, but we simplify things by allowing `tuple.from` to start at midnight, so that there is a full exposure and that we are consistent with our other case.
* `tuple.to` is the end of the date interval. How does this relate to the `Date.Instant` where policy is terminated or where the study ends?
    * if `study_end < termination` then we suppose that the `study_end` means we should include the entire day of `study_end` and the `Dates.Instant` of `tuple.to` is at `23:59.999` military time.
    * if `study_end >= termination` then the termination happens at some time during this day, but we simplify by allowing `tuple.to` to end at `23:59.999`.

In this interpretation the simplification causes some error, maybe some analysis should be done to estimate or put bounds on this error. Maybe this is done in that document from the SOA linked in the description.

**Comment by alecloudenback** [comment]
In the case of a full exposure (e.g. an exposure  `(from = Date("2016-07-04"), to = Date("2017-07-04"))` would be treated as a full year[1]. 

The question you raise: what happens in the opposite case where `from = to = Date(...)`?

I think there's a strong indication in the various `yearfrac` conventions that if given `from = to = Date(...)` that the interval of time represented is zero. 

There's also the ambiguity that is the system producing the experience data. E.g. I think it may be just as likely (or more likely, if I recall from admin data) that a policy that is in force for a single day would look like this:

```
issue date:       2016-07-04 # on risk at 12:01AM
termination date: 2016-07-05 # off risk at 12:01AM
```

Lastly, how would one represent a data point with zero exposure if `from = to` were treated as a full day on-risk? There should be some way to represent zero exposure.

I think this is plausible (a policy is issued, then found to be in error and revoked same day (or backdated to same day).

I'm inclined to say that if you have `d1 = d2 = Date(...)` then it is effectively a null (zero) exposure. This behavior could be documented explicity in the docstring.

@houston what's your thoughts on how `d1 = d2 = Date(...)` exposure should be treated?

**Comment by MatthewCaseres** [comment]
I guess I am arguing that date ranges should be inclusive and should be understood to include the entire day. Consider the behavior of 
```jl
Date(2020,1,1):Day(1):Date(2020,1,3)
```
which yields
```
3-element Vector{Date}:
 2020-01-01
 2020-01-02
 2020-01-03
```

I will have to look at the experience studies report you link in the docs and Matt Heaphy's R package.

**Comment by MatthewCaseres** [comment]
The section in 4.3 on dates is complicated in the experience studies paper, apparently my point on anniversary events depends on the type of study? - 

> For a lapse on a policy anniversary, using 11:59 pm on the day before the anniversary assures that the lapse is allocated to the proper policy year. The date assumption may need to be adjusted for certain events under study. For example, a death on the policy anniversary would be incorrectly assigned to the prior policy year by using 11:59 on the day before. Deaths should therefore be assumed to occur at 11:59 pm on the date of death, not the prior day.

I'm going to close for now since it doesn't seem like either way is really wrong.
